<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160804065654 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE acme_question_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, content VARCHAR(250) NOT NULL, `right` TINYINT(1) NOT NULL, INDEX IDX_209003AEB6F7494E (question), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acme_question_domain_model_course (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(80) NOT NULL, description VARCHAR(250) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acme_question_domain_model_question (persistence_object_identifier VARCHAR(40) NOT NULL, course VARCHAR(40) DEFAULT NULL, content VARCHAR(250) NOT NULL, INDEX IDX_61800BB7169E6FB9 (course), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE acme_question_domain_model_answer ADD CONSTRAINT FK_209003AEB6F7494E FOREIGN KEY (question) REFERENCES acme_question_domain_model_question (persistence_object_identifier)');
        $this->addSql('ALTER TABLE acme_question_domain_model_question ADD CONSTRAINT FK_61800BB7169E6FB9 FOREIGN KEY (course) REFERENCES acme_question_domain_model_course (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE acme_question_domain_model_question DROP FOREIGN KEY FK_61800BB7169E6FB9');
        $this->addSql('ALTER TABLE acme_question_domain_model_answer DROP FOREIGN KEY FK_209003AEB6F7494E');
        $this->addSql('DROP TABLE acme_question_domain_model_answer');
        $this->addSql('DROP TABLE acme_question_domain_model_course');
        $this->addSql('DROP TABLE acme_question_domain_model_question');
    }
}