<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160825121435 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE acme_question_domain_model_answer CHANGE content content VARCHAR(500) NOT NULL');
        $this->addSql('ALTER TABLE acme_question_domain_model_question CHANGE content content VARCHAR(500) NOT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE acme_question_domain_model_answer CHANGE content content VARCHAR(250) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE acme_question_domain_model_question CHANGE content content VARCHAR(250) NOT NULL COLLATE utf8_unicode_ci');
    }
}