#                                                                        #
# Routes configuration for the Question package                          #
#                                                                        #
#
# In order to activate those routes, add the following snippet to the main
# Routes.yaml file of your distribution:
#

-
  name: 'Course index'
  uriPattern: 'courses'
  defaults:
    '@package': 'Acme.Question'
    '@controller': 'Course'
    '@action': 'index'

-
  name: 'Course actions'
  uriPattern: 'courses/{@action}'
  defaults:
    '@controller': 'Course'

-
  name: 'Single course actions'
  uriPattern: 'courses/{course}/{@action}'
  defaults:
    '@controller': 'Course'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'

-
  name: 'Question index'
  uriPattern: 'course/{course}/question'
  defaults:
    '@controller': 'Question'
    '@action': 'index'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'

-
  name: 'Question actions'
  uriPattern: 'course/{course}/question/{@action}'
  defaults:
    '@controller': 'Question'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'

-
  name: 'Single question'
  uriPattern: 'course/{course}/question/{question}'
  defaults:
    '@controller': 'Question'
    '@action': 'show'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'
    question:
      objectType: 'Acme\Question\Domain\Model\Question'

-
  name: 'Single question actions'
  uriPattern: 'course/{course}/question/{question}/{@action}'
  defaults:
    '@controller': 'Question'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'
    question:
      objectType: 'Acme\Question\Domain\Model\Question'

-
  name: 'Answer index'
  uriPattern: 'course/{course}/questions/{question}/answers'
  defaults:
    '@controller': 'Answer'
    '@action': 'index'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'
    question:
      objectType: 'Acme\Question\Domain\Model\Question'

-
  name: 'Answer actions'
  uriPattern: 'course/{course}/question/{question}/answer/{@action}'
  defaults:
    '@controller': 'Answer'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'
    question:
      objectType: 'Acme\Question\Domain\Model\Question'

-
  name: 'Single answer actions'
  uriPattern: 'course/{course}/question/{question}/answer/{answer}/{@action}'
  defaults:
    '@controller': 'Answer'
  routeParts:
    course:
      objectType: 'Acme\Question\Domain\Model\Course'
      uriPattern: '{title}'
    question:
      objectType: 'Acme\Question\Domain\Model\Question'
    answer:
      objectType: 'Acme\Question\Domain\Model\Answer'
